fgenv : Fix /dev/null redirection (2&>1 >/dev/null => >/dev/null 2&>1)

diff --git a/fgenv b/fgenv
--- a/fgenv
+++ b/fgenv
@@ -80,7 +80,7 @@ LIBDIR=${WORKDIR}/lib
 #SCRIPT_DIR=${TOOLKIT_BIN:-/oracle/exploit}
 #[ -x /prsyslib/toolunix/bin ] && SCRIPT_DIR=/prsyslib/toolunix/bin
 #[ -x /oracle/exploit ] && SCRIPT_DIR=/oracle/exploit
-#[ -z "${SCRIPT_DIR}" ] && SCRIPT_DIR=${TOOLKIT_BIN:-$(dirname $(which --skip-alias ora_functions.sh) 2>&1 >/dev/null)}
+#[ -z "${SCRIPT_DIR}" ] && SCRIPT_DIR=${TOOLKIT_BIN:-$(dirname $(which --skip-alias ora_functions.sh) >/dev/null 2>&1)}
 ## FGR 2025-01-15 : Lookup for BI Tools script directory if not previously set
 [ -z "${SCRIPT_DIR}" ] && SCRIPT_DIR=${TOOLKIT_BIN:-$(eval ls -d /prsyslib/toolunix/bin/ 2>/dev/null)}
 ## FGR 2025-01-15 : Lookup for DBATools script directory
@@ -114,7 +114,7 @@ if [ $(hostname | grep -E "dbadm|biexa|bizra") ]; then
   [ $(hostname | grep "biexa") ]          && WELCOME_MSG="Plateform : EXADATA Converged (CNVG)" && PLATFORM_TYPE=EXA_CNVG
   [ $(hostname | grep "bizra") ]          && WELCOME_MSG="Plateform : ZDLRA Converged (CNVG)"   && PLATFORM_TYPE=ZDLRA_CNVG
   [ $(hostname | grep -E "ora[0-9]{4}") ] && WELCOME_MSG="Plateform : EXADATA (NX)"             && PLATFORM_TYPE=EXA_NX
-  alias fgenv 2>&1 >/dev/null || alias fgenv=". ${LIBDIR}/fgenv"
+  alias fgenv >/dev/null 2>&1 || alias fgenv=". ${LIBDIR}/fgenv"
   HN=$(hostname -s)
   HN_BASE=${HN%?}
   HN_NUM=${HN#${HN%?}}
@@ -794,7 +794,7 @@ function lsnGetservice {
     #export -f MainFunc
     #su grid -c "bash -c HOST=$(hostname -s); export ORACLE_SID=+ASM${HOST:0,-1}; export ORAENV_ASK=NO; export PATH=${PATH}:/usr/local/bin/; . oraenv>/dev/null; MainFunc $1"
     #su grid -c "bash -c echo "HOST=$(hostname -s); export ORACLE_SID=+ASM${HOST:0,-1}; export ORAENV_ASK=NO; export PATH=${PATH}:/usr/local/bin/; . oraenv; echo ${ORACLE_SID}:${ORACLE_HOME}; MainFunc $1""
-    sudo -i -u grid bash -c ". ${BI_PATH}/lib/fgenv 2>&1 >/dev/null; export PATH=\$PATH:/usr/local/bin/; HOST=\$(hostname -s); export ORACLE_SID=+ASM\${HOST:0,-1}; export ORAENV_ASK=NO; . oraenv>/dev/null; lsnGetservice $1"
+    sudo -i -u grid bash -c ". ${BI_PATH}/lib/fgenv >/dev/null 2>&1; export PATH=\$PATH:/usr/local/bin/; HOST=\$(hostname -s); export ORACLE_SID=+ASM\${HOST:0,-1}; export ORAENV_ASK=NO; . oraenv>/dev/null; lsnGetservice $1"
     #sudo -u grid bash -c "MainFunc $1"
     #su grid -c "bash -c MainFunc $1"
   fi
@@ -873,17 +873,17 @@ function set_oracle_wallet {
 
 function oracle_wallet_infra {
     local REP_WALLET_INFRA
-    #hostname | grep prdres 2>&1 >/dev/null && ENV=PRD
-    #hostname | grep intres 2>&1 >/dev/null && ENV=HPR
+    #hostname | grep prdres >/dev/null 2>&1 && ENV=PRD
+    #hostname | grep intres >/dev/null 2>&1 && ENV=HPR
     [ "${ENV}" = "HPR" ] && local WALLET_PASSWD=${WALLET_PASSWD:-$(echo "aUZLVVcjSCQhdWhBdHVYCg==" | base64 -d)}
     [ "${ENV}" = "PRD" ] && local WALLET_PASSWD=${WALLET_PASSWD:-$(echo "YXZTU2kjPWRhbUVzUWZHCg==" | base64 -d)}
     # FGR : #orapki wallet change_pwd -wallet ${REP_WALLET_INFRA} -oldpwd '<old_passwd>' -newpwd '<new_passwd>'
-    if $(which --skip-alias mkstore 2>&1 >/dev/null); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
+    if $(which --skip-alias mkstore >/dev/null 2>&1); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
     REP_WALLET_INFRA="${TOOLKIT_DIR:-/prsyslib/toolunix/bin}/ora/wallet_infra"
     export TNS_ADMIN=${REP_WALLET_INFRA}
     echo "TNS_ADMIN=${TNS_ADMIN}"
     [ -z "${WALLET_PASSWD}" ] && read -p "Enter Wallet Password : " -s WALLET_PASSWD
-    if ! $(echo "${WALLET_PASSWD}" | mkstore -wrl ${REP_WALLET_INFRA} -listCredential 2>&1 >/dev/null) ; then echo 'Wrong Wallet password' ; fi
+    if ! $(echo "${WALLET_PASSWD}" | mkstore -wrl ${REP_WALLET_INFRA} -listCredential >/dev/null 2>&1) ; then echo 'Wrong Wallet password' ; fi
     action=${1:-PRINT}
 
     NBR_ENTRIES=$(echo "${WALLET_PASSWD}" | mkstore -wrl ${REP_WALLET_INFRA} -listCredential | grep -c [0-9]:)
@@ -946,8 +946,8 @@ function oracle_wallet_db {
     #export TNS_ADMIN=${WALLET_PATH}
     #echo "TNS_ADMIN=${TNS_ADMIN}"
 
-    #if $(which --skip-alias mkstore 2>&1 >/dev/null); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
-    if ! $(which --skip-alias mkstore 2>&1 >/dev/null); then 
+    #if $(which --skip-alias mkstore >/dev/null 2>&1); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
+    if ! $(which --skip-alias mkstore >/dev/null 2>&1); then 
         echo "mkstore binary not is the path ... Searching ..."
         #if MKSTORE_BIN_PATH=$(dirname `locate -be '\mkstore' | grep grid | tail -1`); 
         #if MKSTORE_BIN_PATH=$(dirname `locate -be '\mkstore' | grep grid | tail -1`); then echo "MKSTORE_BIN_PATH=${MKSTORE_BIN_PATH}"; PATH=${PATH}:${MKSTORE_BIN_PATH}; else echo "! mkstore not found !"; return 0; fi
@@ -961,7 +961,7 @@ function oracle_wallet_db {
     #    echo "MKSTORE_BIN_PATH=${MKSTORE_BIN_PATH}"
     fi
 
-    #if ! $(echo "${WALLET_PASSWD}" | mkstore -wrl ${WALLET_PATH:-.} -listCredential 2>&1 >/dev/null) ; then echo 'Wrong Wallet password' ; fi
+    #if ! $(echo "${WALLET_PASSWD}" | mkstore -wrl ${WALLET_PATH:-.} -listCredential >/dev/null 2>&1) ; then echo 'Wrong Wallet password' ; fi
     #if [ $(echo "${WALLET_PASSWD}" | mkstore -wrl ${WALLET_PATH:-.} ${WLT_DFT_ARGS} -list | grep -c 'incorrect password') -ne 0 ] ; then echo 'Wrong Wallet password' ; return 1; fi
 
     # orapki wallet display -wallet ${WALLET_PATH:-.}
@@ -1107,8 +1107,8 @@ function oracle_wallet_dbatools {
         )
     echo 
 
-    #if $(which --skip-alias mkstore 2>&1 >/dev/null); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
-    if $(which --skip-alias mkstore 2>&1 >/dev/null); then 
+    #if $(which --skip-alias mkstore >/dev/null 2>&1); then echo "ORACLE_HOME=${ORACLE_HOME}"; else echo "ORACLE_HOME not set"; return 0; fi
+    if $(which --skip-alias mkstore >/dev/null 2>&1); then 
         echo "ORACLE_HOME=${ORACLE_HOME}"
     else 
         echo "ORACLE_HOME not set"
@@ -1179,30 +1179,30 @@ function oracle_wallet_dbatools {
 # RMARCHMON Resource
 function lsarchmon {
   local ORACLE_SID=${1:-$ORACLE_SID}
-  ! $(which --skip-alias crsctl 2>&1 >/dev/null) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
+  ! $(which --skip-alias crsctl >/dev/null 2>&1) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
   #crsctl stat res -w "( NAME coi prc. ) AND ( NAME en .arc )"|grep STATE|cut -d ',' -f1,2|sed 's/STATE=/archmon /';
   crsctl stat res -w "( NAME coi prc.${ORACLE_SID:0:8} ) AND ( NAME en .arc )"
 }
 
 function lsarchmon_not_ONLINE {
-  ! $(which --skip-alias crsctl 2>&1 >/dev/null) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
+  ! $(which --skip-alias crsctl >/dev/null 2>&1) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
   crsctl stat res -w "( NAME coi prc. ) AND ( NAME en .arc ) AND (STATE != ONLINE)";
 }
 
 function lsarchmon_sum {
-  ! $(which --skip-alias crsctl 2>&1 >/dev/null) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
+  ! $(which --skip-alias crsctl >/dev/null 2>&1) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
   crsctl stat res -w "(NAME coi arc)" | grep STATE | sort | uniq -c
 }
 
 function lsarchmon_diff {
-  ! $(which --skip-alias crsctl 2>&1 >/dev/null) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
+  ! $(which --skip-alias crsctl >/dev/null 2>&1) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
   printf "%s || %s\n" "ARCHMON without DB <=" "=> Database without ARCHMON"
   sdiff -s -w50 <(crsctl stat res -w "(NAME coi arc)" -t | grep 'prc.*arc' | cut -d. -f2) <(crsctl stat res -w "( TYPE = ora.database.type )" | grep NAME | cut -d. -f2 | tr '[a-z]' '[A-Z]')
 }
 
 function archmon_config_sid {
   local ORACLE_SID=${1:-$ORACLE_SID}
-  ! $(which --skip-alias crsctl 2>&1 >/dev/null) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
+  ! $(which --skip-alias crsctl >/dev/null 2>&1) && { CSSD_DIR=`dirname $( ps -eo args | grep ocssd.bin | grep -v grep | awk '{print $1}' )`; pathmunge $CSSD_DIR after; }
 
   for _NODE in $(crsctl stat res -w "NAME coi ${ORACLE_SID:0:8}" -p | grep "GEN_USR_ORA_INST_NAME@" | sort -u) ; do
     _CLUSTER_NODE=$(echo ${_NODE} | cut -d"(" -f2 | cut -d")" -f1)
@@ -1269,7 +1269,7 @@ alias nmon14g=${BINDIR}/nmon14g_x86_rhel7
 #alias screen='screen -h 50000'
 ## FGR 2022-02-04 : Force the use of the custom screen in case other screen rpm is installed
 #alias screen='${BI_PATH}/bin/screen -h 50000'
-if ! $(which --skip-alias screen 2>&1 >/dev/null); then alias screen='${BI_PATH}/bin/screen -h 50000' else alias screen='screen -h 50000'; fi
+if ! $(which --skip-alias screen >/dev/null 2>&1); then alias screen='${BI_PATH}/bin/screen -h 50000' else alias screen='screen -h 50000'; fi
 alias sc='screen -h 50000'
 alias scls='screen -ls'
 #alias scls='screen -ls | \grep "${1}"'
@@ -1992,15 +1992,15 @@ function ORA_CNX_TEST {
 ## Check Instances connection
 # All instances
 pgrep -af _pmon_ | grep -v '+A' | sort -k2 | awk -F'_' '{ print $NF }' | \
- xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid 2>&1 >/dev/null ; echo "${ORACLE_SID} $(printf "%-18s" `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"`;) `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`"' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*'
-# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid 2>&1 >/dev/null ; printf "%10s %18s => %-6s %s %s %s %s %s %s %s %s %s %s\n" ${ORACLE_SID} `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"` `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*' 
-# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid 2>&1 >/dev/null ; echo ${ORACLE_SID} \(`echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\1.\2.\3.\4.\5:"`\) : `echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nselect * from dual;" | sqlplus -s / as sysdba 2>&1 >/dev/null; [ "$?" = "0"  ] && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO"`' | grep --color -Ei '^|CNX KO'
+ xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid >/dev/null 2>&1 ; echo "${ORACLE_SID} $(printf "%-18s" `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"`;) `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`"' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*'
+# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid >/dev/null 2>&1 ; printf "%10s %18s => %-6s %s %s %s %s %s %s %s %s %s %s\n" ${ORACLE_SID} `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"` `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*' 
+# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid >/dev/null 2>&1 ; echo ${ORACLE_SID} \(`echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\1.\2.\3.\4.\5:"`\) : `echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nselect * from dual;" | sqlplus -s / as sysdba >/dev/null 2>&1; [ "$?" = "0"  ] && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO"`' | grep --color -Ei '^|CNX KO'
 
 
 # Per version
 #ORA_VER=19.22
 #pgrep -af _pmon_ | grep -v '+A' | sort -k2 | while read pid pname ; do echo ${pname#???_pmon_} $(sudo ls -l /proc/$pid/exe | awk -F'>' '{ print $2 }' | sed 's/bin\/oracle$//'); done | grep "${ORA_VER:-|NA|}" | awk '{print $1}' | \
-# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid 2>&1 >/dev/null ; echo "${ORACLE_SID} $(printf "%-18s" `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"`;) `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`"' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*'
+# xargs -P10 -Idbsid sh -c '. oraenv<<<dbsid >/dev/null 2>&1 ; echo "${ORACLE_SID} $(printf "%-18s" `echo "${ORACLE_HOME}" | sed -E "s:.*/([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*)\.([0-9]*).*:\(\1.\2.\3.\4.\5\):"`;) `TEST_DB_CNX_OUT=$(echo -e "WHENEVER SQLERROR EXIT SQL.SQLCODE;\nconnect / as sysdba" | sqlplus -S -L /nolog) && echo "RC=$? : CNX OK" || echo "RC=$? : CNX KO : $(echo -n ${TEST_DB_CNX_OUT})"`"' | grep --color -Ei '^|CNX KO|ERROR|ORA-.*'
 }
 
 
